### ISSUE TITLE
재현 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by SeungKyoJin** [JungoKim/brunch_nafma#1]
안녕하세요. 카카오 아레나에서 준 evaluate.py를 이용해 inference.py 실행 후 재현을 하면
성능이 베이스라인보다 낮게나오는데 혹시 제가 재현하는 방법에 어떤 문제가 있는 것일가요?

**Comment by BryanKoo** [comment]
안녕하세요.

inference.py는 TEST 사용자 5000명에 대해 2/22~3/14까지의 조회를 예측하여 결과를 생성합니다.

카카오 아레나의 evaluate.py는 2/28 까지의 조회 기록으로만 성능을 미리 확인 해보는 용도로 사용하는 것이라서 inference.py 예측 결과의 성능을 확인할 수는 없습니다.

카카오 아레나에 가입하셔서 inference.py 예측 결과를 제출해야 재현할 수 있습니다.
DEV 사용자 3000명에 대해서 예측 결과를 생성하시고 확인해보세요.

"python inference.py dev" 라고 실행하시면 DEV 사용자에 대해 예측 결과를 생성합니다.

**Comment by SeungKyoJin** [comment]
답변해 주셔서 감사합니다! 이해에 더 도움이 되었습니다.
